# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

workflow-executor:
  docker:
    - image: cimg/base:stable
      auth:
        username: $DOCKER_HUB_USER
        password: $DOCKER_HUB_PASSWORD

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    executor: workflow-executor
    steps:
      - checkout
      - run: chmod +x ./gradlew
      - run: ./gradlew build
  

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build:
    jobs:
      - build
